language: node_js
node_js: '8'
os: linux
dist: bionic
services:
- docker
cache: npm
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
install:
- npm install
- npm update
script: ci/script.sh
after_success: npm run codecov
